# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.22.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.22.0/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/bingweiwang/Documents/GitHub/FastCode_Image_Filter

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/bingweiwang/Documents/GitHub/FastCode_Image_Filter

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.22.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.22.0/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bingweiwang/Documents/GitHub/FastCode_Image_Filter/CMakeFiles /Users/bingweiwang/Documents/GitHub/FastCode_Image_Filter//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bingweiwang/Documents/GitHub/FastCode_Image_Filter/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named duo_tone

# Build rule for target.
duo_tone: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 duo_tone
.PHONY : duo_tone

# fast build rule for target.
duo_tone/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/duo_tone.dir/build.make CMakeFiles/duo_tone.dir/build
.PHONY : duo_tone/fast

#=============================================================================
# Target rules for targets named duo_tone_ref

# Build rule for target.
duo_tone_ref: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 duo_tone_ref
.PHONY : duo_tone_ref

# fast build rule for target.
duo_tone_ref/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/duo_tone_ref.dir/build.make CMakeFiles/duo_tone_ref.dir/build
.PHONY : duo_tone_ref/fast

duo_tone.o: duo_tone.cpp.o
.PHONY : duo_tone.o

# target to build an object file
duo_tone.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/duo_tone.dir/build.make CMakeFiles/duo_tone.dir/duo_tone.cpp.o
.PHONY : duo_tone.cpp.o

duo_tone.i: duo_tone.cpp.i
.PHONY : duo_tone.i

# target to preprocess a source file
duo_tone.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/duo_tone.dir/build.make CMakeFiles/duo_tone.dir/duo_tone.cpp.i
.PHONY : duo_tone.cpp.i

duo_tone.s: duo_tone.cpp.s
.PHONY : duo_tone.s

# target to generate assembly for a file
duo_tone.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/duo_tone.dir/build.make CMakeFiles/duo_tone.dir/duo_tone.cpp.s
.PHONY : duo_tone.cpp.s

duo_tone_ref.o: duo_tone_ref.cpp.o
.PHONY : duo_tone_ref.o

# target to build an object file
duo_tone_ref.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/duo_tone_ref.dir/build.make CMakeFiles/duo_tone_ref.dir/duo_tone_ref.cpp.o
.PHONY : duo_tone_ref.cpp.o

duo_tone_ref.i: duo_tone_ref.cpp.i
.PHONY : duo_tone_ref.i

# target to preprocess a source file
duo_tone_ref.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/duo_tone_ref.dir/build.make CMakeFiles/duo_tone_ref.dir/duo_tone_ref.cpp.i
.PHONY : duo_tone_ref.cpp.i

duo_tone_ref.s: duo_tone_ref.cpp.s
.PHONY : duo_tone_ref.s

# target to generate assembly for a file
duo_tone_ref.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/duo_tone_ref.dir/build.make CMakeFiles/duo_tone_ref.dir/duo_tone_ref.cpp.s
.PHONY : duo_tone_ref.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... duo_tone"
	@echo "... duo_tone_ref"
	@echo "... duo_tone.o"
	@echo "... duo_tone.i"
	@echo "... duo_tone.s"
	@echo "... duo_tone_ref.o"
	@echo "... duo_tone_ref.i"
	@echo "... duo_tone_ref.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

